[project]
name = "calix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "importlib-metadata>=8.7.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "xortool==1.0.0",
]
